### ISSUE TITLE
Helios Megapolity's Dome Colonizers cannot found cities

### ISSUE THREAD

**Issue by JohnTelles** [carriontrooper/Alpha-Frontier-New-Powers-Addon#3]
Dome Colonizers (settlers from Helios Megapolity civilization) do not have the button to found a new city, no matter the initial position.

**Comment by carriontrooper** [comment]
Yeah, my bad - tried to update with new conditionals.
Partially fixed for the first dome colonizer.

**Comment by JohnTelles** [comment]
Thank you very much. I love your work on Alpha Frontier. Best wishes.
